# ==========================
# DATABASE CONFIGURATION
# ==========================

spring.datasource.url=jdbc:postgresql://localhost:5432/aa_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA CONFIGURATION
# ==========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# SERVER CONFIGURATION
# ==========================

server.port=8080

# ==========================
# SESSION CONFIGURATION
# ==========================

server.servlet.session.timeout=30m

# ==========================
# LOGGING
# ==========================

logging.level.root=INFO
logging.level.com.dheeraj.aa=DEBUG

# ==========================
# DIGIO CONFIG
# ==========================

digio.base.url=https://ext.digio.in:444/fiu_api
digio.username=YOUR_DIGIO_USERNAME
digio.password=YOUR_DIGIO_PASSWORD
digio.template.id=YOUR_TEMPLATE_ID

# ==========================
# GEN AI CONFIG
# ==========================

genai.api.url=https://api.openai.com/v1/chat/completions
genai.api.key=YOUR_API_KEY_HERE
